# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  customer-service:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.CustomerService"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ozon.route256.practice.customerservice:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.CustomerService:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.2\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_27_02_14_44:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  logistic-simulator:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.LogisticsSimulator"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ozon.route256.practice.logisticssimulator:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.LogisticsSimulator:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.2\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_27_02_14_44:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  orders-generator-api:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.OrdersGenerator"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57402"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ozon.route256.practice.ordersgenerator:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57402"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.OrdersGenerator:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.2\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_27_02_14_44:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  orders-generator-mobile:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.OrdersGenerator"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ozon.route256.practice.ordersgenerator:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.OrdersGenerator:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.2\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_27_02_14_44:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  orders-generator-web:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.OrdersGenerator"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57404"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ozon.route256.practice.ordersgenerator:dev"
    ports:
    - "127.0.0.1:57004:57000"
    - "127.0.0.1:57204:57200"
    - "127.0.0.1:57404:57404"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.OrdersGenerator:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.2\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_27_02_14_44:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  service-discovery:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.ServiceDiscovery"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57405"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ozon.route256.practice.servicediscovery:dev"
    ports:
    - "127.0.0.1:57005:57000"
    - "127.0.0.1:57205:57200"
    - "127.0.0.1:57405:57405"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1\\src\\Ozon.Route256.Practice.ServiceDiscovery:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\homework-1:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.2\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_27_02_14_44:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
